// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {repository} from '../models';

export function AddTask(arg1:repository.Task):Promise<number>;

export function DeleteTask(arg1:number):Promise<void>;

export function GetTasks():Promise<Array<repository.Task>>;

export function UpdateTask(arg1:repository.Task):Promise<void>;
